"""
Convert Element10.jpg (bottom color texture) + Element0.jpg (top height map)
into a 3in x 3in x 1/8in STL tile.

Dimensions:
  Width  = 76.2mm  (3 inches)
  Height = 76.2mm  (3 inches)
  Depth  = 3.175mm (1/8 inch) - base thickness + height displacement

The top surface is displaced by the grayscale value in Element0.jpg.
White (255) = maximum height (full 3.175mm), black (0) = minimum height.
We use a base of 2.0mm and relief up to 1.175mm so the piece always has
some thickness everywhere.
"""

import struct
import math
from PIL import Image

WIDTH_MM  = 76.2
HEIGHT_MM = 76.2
TOTAL_DEPTH_MM = 3.175
BASE_THICKNESS = 2.0          # flat bottom to mid-level
RELIEF_DEPTH   = TOTAL_DEPTH_MM - BASE_THICKNESS  # 1.175mm of relief

INPUT_HEIGHTMAP = "c:/Users/hasse/OneDrive/Documents/git/MRR/images/Element0.jpg"
OUTPUT_STL      = "c:/Users/hasse/OneDrive/Documents/git/MRR/images/Element10.stl"

# Resolution: subsample the 301x301 image to a manageable grid.
# 100x100 grid = ~10000 quads = ~20000 triangles (fast, still detailed)
GRID_W = 100
GRID_H = 100

def load_heightmap(path, grid_w, grid_h):
    img = Image.open(path).convert("L")  # grayscale
    img = img.resize((grid_w, grid_h), Image.LANCZOS)
    pixels = list(img.getdata())
    return pixels, grid_w, grid_h

def height_at(pixels, gw, x, y):
    """Return Z height in mm for grid cell (x,y). 0,0 = bottom-left."""
    val = pixels[y * gw + x] / 255.0   # 0.0 .. 1.0
    return BASE_THICKNESS + val * RELIEF_DEPTH

def normal(v0, v1, v2):
    ax, ay, az = v1[0]-v0[0], v1[1]-v0[1], v1[2]-v0[2]
    bx, by, bz = v2[0]-v0[0], v2[1]-v0[1], v2[2]-v0[2]
    nx = ay*bz - az*by
    ny = az*bx - ax*bz
    nz = ax*by - ay*bx
    length = math.sqrt(nx*nx + ny*ny + nz*nz)
    if length == 0:
        return (0.0, 0.0, 1.0)
    return (nx/length, ny/length, nz/length)

def write_triangle(f, v0, v1, v2):
    n = normal(v0, v1, v2)
    f.write(struct.pack('<3f', *n))
    f.write(struct.pack('<3f', *v0))
    f.write(struct.pack('<3f', *v1))
    f.write(struct.pack('<3f', *v2))
    f.write(struct.pack('<H', 0))  # attribute byte count

def main():
    print("Loading height map...")
    pixels, gw, gh = load_heightmap(INPUT_HEIGHTMAP, GRID_W, GRID_H)

    # Build vertex grid for top surface
    # Grid has (GRID_W+1) x (GRID_H+1) vertices
    GVW = gw + 1
    GVH = gh + 1

    def vertex_x(ix):
        return (ix / gw) * WIDTH_MM

    def vertex_y(iy):
        return (iy / gh) * HEIGHT_MM

    def top_z(ix, iy):
        # clamp
        cx = min(ix, gw - 1)
        cy = min(iy, gh - 1)
        return height_at(pixels, gw, cx, cy)

    # Count triangles:
    # Top surface:   2 triangles per quad = gw*gh*2
    # Bottom surface: 2 triangles per quad = gw*gh*2
    # 4 side walls, each has gh or gw quads, each quad = 2 triangles
    #   left/right walls: gh quads each
    #   front/back walls: gw quads each
    top_tris    = gw * gh * 2
    bottom_tris = gw * gh * 2
    side_tris   = 2 * (gh * 2 + gw * 2)
    total_tris  = top_tris + bottom_tris + side_tris

    print(f"Grid: {gw}x{gh}, Total triangles: {total_tris}")
    print(f"Writing STL to {OUTPUT_STL}...")

    with open(OUTPUT_STL, 'wb') as f:
        # 80-byte header
        header = b'Element10 3x3x0.125in STL generated by generate_stl.py'
        header = header.ljust(80, b'\x00')
        f.write(header)
        f.write(struct.pack('<I', total_tris))

        # --- TOP SURFACE ---
        for iy in range(gh):
            for ix in range(gw):
                x0 = vertex_x(ix);     x1 = vertex_x(ix+1)
                y0 = vertex_y(iy);     y1 = vertex_y(iy+1)
                z00 = top_z(ix,   iy)
                z10 = top_z(ix+1, iy)
                z01 = top_z(ix,   iy+1)
                z11 = top_z(ix+1, iy+1)
                # Two triangles per quad (CCW from above = normal pointing +Z)
                write_triangle(f, (x0,y0,z00), (x1,y0,z10), (x1,y1,z11))
                write_triangle(f, (x0,y0,z00), (x1,y1,z11), (x0,y1,z01))

        # --- BOTTOM SURFACE (flat at z=0, normal pointing -Z) ---
        for iy in range(gh):
            for ix in range(gw):
                x0 = vertex_x(ix);  x1 = vertex_x(ix+1)
                y0 = vertex_y(iy);  y1 = vertex_y(iy+1)
                # CCW from below = normal pointing -Z
                write_triangle(f, (x0,y0,0), (x1,y1,0), (x1,y0,0))
                write_triangle(f, (x0,y0,0), (x0,y1,0), (x1,y1,0))

        # --- SIDE WALLS ---
        # Front wall: y=0, ix from 0..gw, normal pointing -Y
        for ix in range(gw):
            x0 = vertex_x(ix);  x1 = vertex_x(ix+1)
            z0 = top_z(ix,   0)
            z1 = top_z(ix+1, 0)
            write_triangle(f, (x0,0,0),  (x1,0,z1), (x1,0,0))
            write_triangle(f, (x0,0,0),  (x0,0,z0), (x1,0,z1))

        # Back wall: y=HEIGHT_MM, ix from 0..gw, normal pointing +Y
        for ix in range(gw):
            x0 = vertex_x(ix);  x1 = vertex_x(ix+1)
            z0 = top_z(ix,   gh-1)
            z1 = top_z(ix+1, gh-1)
            yb = HEIGHT_MM
            write_triangle(f, (x0,yb,0),  (x1,yb,0), (x1,yb,z1))
            write_triangle(f, (x0,yb,0),  (x1,yb,z1), (x0,yb,z0))

        # Left wall: x=0, iy from 0..gh, normal pointing -X
        for iy in range(gh):
            y0 = vertex_y(iy);  y1 = vertex_y(iy+1)
            z0 = top_z(0, iy)
            z1 = top_z(0, iy+1)
            write_triangle(f, (0,y0,0),  (0,y0,z0), (0,y1,z1))
            write_triangle(f, (0,y0,0),  (0,y1,z1), (0,y1,0))

        # Right wall: x=WIDTH_MM, iy from 0..gh, normal pointing +X
        for iy in range(gh):
            y0 = vertex_y(iy);  y1 = vertex_y(iy+1)
            z0 = top_z(gw-1, iy)
            z1 = top_z(gw-1, iy+1)
            xr = WIDTH_MM
            write_triangle(f, (xr,y0,0),  (xr,y1,0), (xr,y1,z1))
            write_triangle(f, (xr,y0,0),  (xr,y1,z1), (xr,y0,z0))

    import os
    size = os.path.getsize(OUTPUT_STL)
    print(f"Done! File size: {size:,} bytes ({size/1024:.1f} KB)")
    print(f"Output: {OUTPUT_STL}")

if __name__ == "__main__":
    main()
